language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
before_script:
  - python manage.py makemigrations --check --dry-run
  - python manage.py migrate
script:
  - mypy -p new_dawn_server.modules
  - python pre_tests.py
  - python manage.py test 
