# Generated by Django 2.1.1 on 2018-11-27 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='block_metadata',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='actions.UserToUserActionMetadata'),
        ),
        migrations.AlterField(
            model_name='like',
            name='like_metadata',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='actions.UserToUserActionMetadata'),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_metadata',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='actions.UserToUserActionMetadata'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='relationship_metadata',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='actions.UserToUserActionMetadata'),
        ),
        migrations.AlterField(
            model_name='usertouseractionmetadata',
            name='user_account_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='users.Account'),
        ),
        migrations.AlterField(
            model_name='usertouseractionmetadata',
            name='user_account_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='users.Account'),
        ),
    ]
