# Generated by Django 2.1.3 on 2019-01-23 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0002_auto_20181127_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertouseractionmetadata',
            name='entity_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usertouseractionmetadata',
            name='entity_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
