# Generated by Django 2.1.3 on 2019-01-27 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20190127_1750'),
        ('actions', '0004_auto_20190122_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.IntegerField(blank=True, null=True)),
                ('entity_id', models.IntegerField(blank=True, null=True)),
                ('entity_type', models.IntegerField(blank=True, null=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('user_account_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='users.Account')),
                ('user_account_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='users.Account')),
            ],
        ),
        migrations.RemoveField(
            model_name='block',
            name='block_metadata',
        ),
        migrations.RemoveField(
            model_name='like',
            name='like_metadata',
        ),
        migrations.RemoveField(
            model_name='match',
            name='match_metadata',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='relationship_metadata',
        ),
        migrations.RemoveField(
            model_name='usertouseractionmetadata',
            name='user_account_from',
        ),
        migrations.RemoveField(
            model_name='usertouseractionmetadata',
            name='user_account_to',
        ),
        migrations.DeleteModel(
            name='Block',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.DeleteModel(
            name='Relationship',
        ),
        migrations.DeleteModel(
            name='UserToUserActionMetadata',
        ),
    ]
