# Generated by Django 2.1.3 on 2019-02-06 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('actions', '0005_auto_20190127_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraction',
            name='user_account_from',
        ),
        migrations.RemoveField(
            model_name='useraction',
            name='user_account_to',
        ),
        migrations.AddField(
            model_name='useraction',
            name='user_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useraction',
            name='user_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
