# Generated by Django 2.1.3 on 2019-02-21 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0006_auto_20190206_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraction',
            name='message',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
