# Generated by Django 2.1.1 on 2018-11-27 05:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('users', '0009_auto_20181126_2058'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0002_auto_20181127_0035'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnswerQuestions',
            new_name='AnswerQuestion',
        ),
    ]
