# Generated by Django 2.1.1 on 2018-11-27 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20181127_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerquestion',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
