# Generated by Django 2.1.1 on 2018-12-08 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20181202_1422'),
        ('questions', '0004_auto_20181127_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerquestion',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
        ),
    ]
