# Generated by Django 2.1.1 on 2018-12-08 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_answerquestion_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerquestion',
            name='user_profile',
        ),
    ]
