# Generated by Django 2.1.3 on 2018-12-12 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_answerquestion_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerquestion',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Profile'),
        ),
    ]
