# Generated by Django 2.1.3 on 2019-04-06 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_question_user_defined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerquestion',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
        ),
    ]
