# Generated by Django 2.1.1 on 2018-11-19 01:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_auto_20181118_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateField(auto_now_add=True)),
                ('user_account_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toblock', to='users.Account')),
                ('user_account_blocked', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fromblock', to='users.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(blank=True)),
                ('update_time', models.DateField(default=datetime.datetime.now)),
                ('user_account_given', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tograde', to='users.Account')),
                ('user_account_received', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fromgrade', to='users.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.BooleanField(blank=True)),
                ('like_time', models.DateField(auto_now_add=True)),
                ('user_profile_like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tolike', to='users.Profile')),
                ('user_profile_liked', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fromlike', to='users.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_relationship', models.IntegerField(blank=True)),
                ('update_time', models.DateField(default=datetime.datetime.now)),
                ('user_account_relationship_invite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='torelation', to='users.Account')),
                ('user_account_relationship_receive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromrelation', to='users.Account')),
            ],
        ),
    ]
