college_names = ['Bay Mills Community College', 'Central Carolina Technical College', 'Aveda Institute Tucson',
                 'Cloud County Community College', 'Onondaga Community College', 'Georgetown University',
                 'Philadelphia Technician Training', 'Jefferson Technical College', 'Cinta Aveda Institute',
                 'Amarillo College', 'Eastern Florida State College', 'Hondros College of Nursing',
                 'Central Wyoming College', 'EDIC College', 'Rollins College', 'Blue Ridge Community College',
                 'Presentation College', 'Bergen County Technical Schools', 'Scott College of Cosmetology',
                 'University of the Virgin Islands', 'North Dakota State College of Science',
                 'Northwest Hair Academy, Mount Vernon', 'Pueblo Community College', 'Saint Paul School of Theology',
                 'Kaplan Test Prep', 'The Academy of Barbering Arts, Inc.', 'New Horizons Medical Institute',
                 'William Paterson University of New Jersey', 'Defense Acquisition University', 'ASA College',
                 'University of Iowa', 'Mount Carmel College of Nursing', 'Wake Technical Community College',
                 'East Central College', "Prince George's Community College", 'SUNY Potsdam', 'Pensacola State College',
                 'California State University - Channel Islands', 'Westwood College - Los Angeles',
                 'Mount Washington College', 'University of Wyoming', 'Eli Whitney Technical High School',
                 'Franklin Career Colleges, Inc. - Ontario', 'Jones County Junior College',
                 'Metropolitan Community College', 'All Beauty College', 'New Hampshire Institute of Art',
                 'Purdue University Northwest', 'Drexel University', 'Murray State University',
                 'Bergen Community College', 'University of Minnesota - Twin Cities',
                 'Paul Mitchell the School Fayetteville', 'Zane State College', 'Ranken Technical College',
                 'Rogers State University', 'Southern Illinois University Edwardsville',
                 'Allen School of Health Sciences', 'Salus University', 'Carolina Beauty College 8',
                 'Pierpont Community and Technical College', 'Boca Beauty Academy',
                 'Cincinnati State Technical and Community College', 'Metropolitan Community College - Kansas City',
                 'Wayne State College', 'Bellefonte Academy of Beauty', 'Stenotype Institute of Jacksonville Inc',
                 'Inter American University of Puerto Rico Ponce', 'University of the Sciences',
                 'University of Sioux Falls', 'Charleston Southern University', 'Curry College', 'Stark State College',
                 'Orangeburg Calhoun Technical College', 'CHRISTUS SPOHN Hospital Corpus Christi',
                 'John Marshall Law School - Atanta', 'Central Community College', 'Tarleton State University',
                 'Southeastern Illinois College', 'Okaloosa Technical College and Choice High School',
                 'The Scripps Research Institute', 'Seguin Beauty School', 'Brescook, LLC Dale Carnegie Training',
                 'Old Dominion University', 'Navarro College', "L'Academie de Cuisine", 'Wilmington University',
                 'StenoTech Career Institute - Piscataway', 'Texas A&M Health Science Center',
                 'Pacific College of Oriental Medicine', 'California College-San Diego',
                 'Center for Explosive Ordnance Disposal and Diving', 'Germanna Community College',
                 'San Jacinto College District', 'Camphill Academy', 'Black Hills State University',
                 'University of Maine', 'Marinello School of Beauty - Topeka',
                 'International School of Health, Beauty & Technology', 'Salon Success Academy']
