# Generated by Django 2.1.3 on 2018-12-19 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='media',
            field=models.ImageField(upload_to='media/images/'),
        ),
    ]
