# Generated by Django 2.1.3 on 2018-12-19 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0002_auto_20181218_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='media',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
