# Generated by Django 2.1.3 on 2019-04-13 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0005_auto_20190406_0952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['order']},
        ),
    ]
