# Generated by Django 2.1.1 on 2018-11-12 02:59

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_account_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='account',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='000000000', max_length=128),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(default='new york', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='employer',
            field=models.CharField(default='google', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='height',
            field=models.DecimalField(decimal_places=2, default='1.12', max_digits=2),
        ),
        migrations.AddField(
            model_name='profile',
            name='job_title',
            field=models.CharField(default='analyst', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='school',
            field=models.CharField(default='nyu', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='smoke',
            field=models.BooleanField(default=True),
        ),
    ]
