# Generated by Django 2.1.1 on 2018-11-12 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20181111_2334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='city',
            new_name='city_preference',
        ),
        migrations.AddField(
            model_name='profile',
            name='hometown',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
