# Generated by Django 2.1.1 on 2018-11-26 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_answer_questions'),
        ('users', '0007_auto_20181123_0339'),
    ]

    operations = [
    ]
