# Generated by Django 2.1.3 on 2018-12-12 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20181211_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city_preference',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
