# Generated by Django 2.1.3 on 2018-12-12 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_profile_city_preference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='city_preference',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='city_preference',
        ),
    ]
