# Generated by Django 2.1.3 on 2018-12-12 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_auto_20181212_0008'),
        ('users', '0013_auto_20181211_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='city_preference',
            field=models.ManyToManyField(blank=True, null=True, to='locations.CityPreference'),
        ),
    ]
