# Generated by Django 2.1.3 on 2018-12-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_profile_answer_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='city_preference',
            field=models.ManyToManyField(to='locations.CityPreference'),
        ),
    ]
