# Generated by Django 2.1.3 on 2019-01-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20190105_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='city_preference',
            field=models.ManyToManyField(blank=True, to='locations.CityPreference'),
        ),
    ]
