# Generated by Django 2.1.3 on 2019-01-27 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20190126_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='city_preference',
            field=models.ManyToManyField(to='locations.CityPreference'),
        ),
    ]
