# Generated by Django 2.1.3 on 2019-06-18 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_profile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='review_status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
